Description: Server to host Plausible analytics
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  LatestLinuxAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64
  ProjectTag:
    Type: String
    Default: Plausible

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: !ImportValue network-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-security-group"
        - Key: "Project"
          Value: !Ref ProjectTag
  
  NetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: "Network interface for the ${ProjectTag} instance"
      GroupSet:
        - !Ref SecurityGroup
      SubnetId: !ImportValue network-public-subnet
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-network-interface"
        - Key: "Project"
          Value: !Ref ProjectTag

  PlausibleServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t4g.nano
      ImageId: !Ref LatestLinuxAmiId
      KeyName: PlausibleServer
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref NetworkInterface
          DeviceIndex: 0
      UserData:
        Fn::Base64: |
          #!/bin/bash
          dnf update -y
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-server"
        - Key: Project
          Value: !Ref ProjectTag